version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
    - db
    environment:
    - "DJANGO_SECRET_KEY=django-insecure-492sh)w^u)^(!iylmt@yq^lvgx5c%)h7g0t-%s)h-xe-8ny(4l"
    - "DJANGO_SECURE_SSL_REDIRECT=False"
    - "DJANGO_DEBUG=True"
    - "DJANGO_SECURE_HSTS_SECONDS=0"
    - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
    - "DJANGO_SECURE_HSTS_PRELOAD=False"
    - "DJANGO_SESSION_COOKIE_SECURE=False"
    - "DJANGO_CSRF_COOKIE_SECURE=False"
    - "EMAIL_HOST="
    - "EMAIL_HOST_USER="
    - "EMAIL_HOST_PASSWORD="
    - "EMAIL_PORT="
    - "EMAIL_USE_TLS="
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  
volumes:
  postgres_data: