version: "3.9"

services:
  web:
    build: .
    command: gunicorn neverdrugs.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
    - db
    environment:
    - "DJANGO_SECRET_KEY=django-insecure-492sh)w^u)^(!iylmt@yq^lvgx5c%)h7g0t-%s)h-xe-8ny(4l"
    - "DJANGO_SECURE_SSL_REDIRECT=False"
    - "DJANGO_DEBUG=True"
    - "DJANGO_SECURE_HSTS_SECONDS=0"
    - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
    - "DJANGO_SECURE_HSTS_PRELOAD=False"
    - "DJANGO_SESSION_COOKIE_SECURE=False"
    - "DJANGO_CSRF_COOKIE_SECURE=False"
    - "EMAIL_HOST="
    - "EMAIL_HOST_USER="
    - "EMAIL_HOST_PASSWORD="
    - "EMAIL_PORT="
    - "EMAIL_USE_TLS="
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  mjml:
    image: liminspace/mjml-tcpserver:latest
    restart: always
    environment:
      HOST: "0.0.0.0"
      PORT: "28102"
      MJML_ARGS: "--mjml.minify=true --mjml.validationLevel=strict"
    expose:
      - "28102"
    ports:
      - "28102:28102"
volumes:
  postgres_data: