# Generated by Django 4.0.5 on 2022-07-09 10:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aliases', models.CharField(max_length=1023)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aliases', models.CharField(max_length=1023)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('NA', 'Not applicable'), ('MI', 'Mild'), ('MO', 'Moderate'), ('SE', 'Severe')], default='NA', max_length=2)),
                ('evidence', models.CharField(choices=[('L1', 'Systematic review of RCTs'), ('L2', 'Well-designed RCT'), ('L3', 'Well-designed study without randomisation'), ('L4', 'Well designed case-control or cohort studies'), ('L5', 'Reviews of qualitative studies'), ('L6', 'Single qualitative study'), ('L7', 'Expert body opinion')], default='L7', max_length=2)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactions.condition')),
                ('drugs', models.ManyToManyField(to='reactions.drug')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_class',
            field=models.ManyToManyField(to='reactions.drugclass'),
        ),
    ]
