# Generated by Django 4.0.5 on 2022-07-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_alter_condition_aliases_alter_condition_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='condition',
        ),
        migrations.AddField(
            model_name='interaction',
            name='condition',
            field=models.ManyToManyField(to='reactions.condition'),
        ),
    ]
