# Generated by Django 4.0.5 on 2022-07-15 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0003_remove_interaction_condition_interaction_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='condition',
            new_name='conditions',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='reaction_type',
            new_name='name',
        ),
    ]
