# Generated by Django 4.0.5 on 2022-07-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0005_condition_description_drugclass_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL title'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL title'),
        ),
    ]
