# Generated by Django 4.0.5 on 2022-07-18 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0006_alter_condition_slug_alter_drug_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condition',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='ready_to_publish',
            field=models.BooleanField(default=False, verbose_name='Ready to publish?'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='ready_to_publish',
            field=models.BooleanField(default=False, verbose_name='Ready to publish?'),
        ),
    ]
