# Generated by Django 4.0.5 on 2022-07-18 05:02

from django.db import migrations, models
import reactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0007_condition_date_created_condition_date_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', reactions.models.LowercaseField(max_length=255, verbose_name='Article title')),
                ('publication', reactions.models.LowercaseField(max_length=255, verbose_name='Journal or publication name')),
                ('reference', models.TextField(blank=True, max_length=1023, verbose_name='Full reference')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='source',
            field=models.ManyToManyField(to='reactions.source'),
        ),
    ]
