# Generated by Django 4.0.5 on 2022-07-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0012_condition_last_edited_by_drug_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='secondary_drugs',
            field=models.ManyToManyField(related_name='secondary_interactions', to='reactions.drug'),
        ),
    ]
