# Generated by Django 4.0.5 on 2022-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0014_alter_interaction_drugs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='condition_sources', to='reactions.source'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='secondary_conditions',
            field=models.ManyToManyField(blank=True, related_name='secondary_condition_interactions', to='reactions.condition', verbose_name='Conditions with a theoretical link to the interaction'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conditions',
            field=models.ManyToManyField(related_name='interactions', to='reactions.condition', verbose_name='Conditions strongly linked with the interaction'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='secondary_drugs',
            field=models.ManyToManyField(blank=True, related_name='secondary_drug_interactions', to='reactions.drug', verbose_name='Drugs to use with caution'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='interaction_sources', to='reactions.source'),
        ),
    ]
