# Generated by Django 4.0.5 on 2022-08-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0015_condition_sources_interaction_secondary_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of publication'),
        ),
    ]
