# Generated by Django 4.0.5 on 2022-08-14 04:59

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0016_source_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='description',
            field=markdownx.models.MarkdownxField(help_text='Add basic formatting using <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank" rel="noopener noreferrer">Markdown (cheat sheet)</a><br>A live preview of formatted content is shown next to the input field'),
        ),
    ]
