# Generated by Django 4.0.5 on 2022-08-22 05:57

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0017_alter_interaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='peer_review_status',
            field=models.CharField(choices=[('DR', 'Draft'), ('MO', 'Requires modifications, then re-review'), ('AM', 'Accepted after minor changes'), ('AC', 'Accepted')], default='DR', max_length=2),
        ),
        migrations.AddField(
            model_name='interaction',
            name='ready_for_peer_review',
            field=models.BooleanField(default=False, verbose_name='Ready for peer review?'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='description',
            field=markdownx.models.MarkdownxField(help_text='Add basic formatting using <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank"                 rel="noopener noreferrer">Markdown (cheat sheet)</a><br>A live preview of formatted content         is shown next to the input field'),
        ),
    ]
