# Generated by Django 4.0.5 on 2022-11-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0018_interaction_peer_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='peer_review_status',
            field=models.CharField(choices=[('DR', 'Draft'), ('MO', 'Requires modifications, then re-review'), ('AM', 'Accepted after minor changes'), ('AC', 'Accepted')], default='DR', max_length=2),
        ),
        migrations.AddField(
            model_name='condition',
            name='ready_for_peer_review',
            field=models.BooleanField(default=False, verbose_name='Ready for peer review?'),
        ),
    ]
