# Generated by Django 4.0.5 on 2022-11-26 10:17

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0019_condition_peer_review_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='peer_review_status',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='ready_for_peer_review',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='ready_to_publish',
        ),
        migrations.AddField(
            model_name='condition',
            name='evidence',
            field=models.CharField(choices=[('L1', 'Systematic review of RCTs'), ('L2', 'Well-designed RCT'), ('L3', 'Well-designed controlled study without randomisation'), ('L4', 'Well designed case-control or cohort studies'), ('L5', 'Reviews of qualitative studies'), ('L6', 'Single qualitative study'), ('L7', 'Expert body opinion')], default='L7', max_length=2),
        ),
        migrations.AddField(
            model_name='interaction',
            name='include_article',
            field=models.BooleanField(default=False, help_text='Include this article if many conditions         lead to the same endpoint (i.e. malignant hyperthermia)', verbose_name='Include this article on the website?'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='URL title'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Add basic formatting using <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank"                 rel="noopener noreferrer">Markdown (cheat sheet)</a><br>A live preview of formatted content         is shown next to the input field', null=True),
        ),
    ]
