# Generated by Django 4.1.3 on 2023-02-03 01:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0022_alter_condition_aliases_alter_condition_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Add basic formatting using <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank" rel="noopener noreferrer">Markdown (cheat sheet)</a><br>A live preview of formatted content     is shown next to the input field', null=True, verbose_name='Article body'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Add basic formatting using <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank" rel="noopener noreferrer">Markdown (cheat sheet)</a><br>A live preview of formatted content     is shown next to the input field', null=True, verbose_name='Article body - not displayed by default'),
        ),
    ]
