# Generated by Django 4.1.7 on 2023-03-08 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0026_drug_description_alter_condition_see_also'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
