# Generated by Django 4.0.5 on 2022-07-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='default_slug', unique=False),
            preserve_default=False,
        ),
    ]
