# Generated by Django 4.1.3 on 2023-02-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('access_peer_review', 'Can access the peer review module'),)},
        ),
    ]
