# Generated by Django 4.0.5 on 2022-08-22 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reactions', '0018_interaction_peer_review_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', markdownx.models.MarkdownxField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('actioned', models.BooleanField(default=False)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='reactions.interaction')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('open', models.BooleanField(default=False)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL, verbose_name='Host for the peer review session')),
                ('interaction_reviews', models.ManyToManyField(blank=True, related_name='interaction_reviews', to='review.interactionreview')),
                ('user_list', models.ManyToManyField(blank=True, related_name='user_list', to=settings.AUTH_USER_MODEL, verbose_name='Users present during the peer review session')),
            ],
        ),
    ]
