# Generated by Django 4.0.5 on 2022-08-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0018_interaction_peer_review_status_and_more'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InteractionReview',
            new_name='Review',
        ),
    ]
