# Generated by Django 4.0.5 on 2022-11-16 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_rename_interactionreview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='update',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='last_ajax',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL, verbose_name='Chairperson for the meeting'),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='interaction_reviews',
            field=models.ManyToManyField(blank=True, related_name='interaction_reviews', to='review.review', verbose_name='Interactions for peer review'),
        ),
    ]
