# Generated by Django 4.1.3 on 2023-02-03 01:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_review_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='reviewsession',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=markdownx.models.MarkdownxField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='update',
            field=markdownx.models.MarkdownxField(blank=True, default='', null=True),
        ),
    ]
