# Generated by Django 4.0.5 on 2022-08-03 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=255)),
                ('drugs', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=1023)),
                ('admin_notes', models.TextField(blank=True, max_length=1023)),
                ('actioned', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_edited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
