# Generated by Django 4.0.5 on 2022-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_condition_remove_ticket_drugs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='for_review',
            field=models.BooleanField(default=False, verbose_name='Mark for review'),
        ),
    ]
